// client-vue/src/pages/ListPage.vue
<!--
  列表页：当前空间下所有用例 + 空间切换 + 新建/删除用例 + 成员管理
  数据流：
    - 空间：useSpaceStore（持久化 currentId 到 localStorage）
    - 登录用户：useAuthStore
    - 用例列表：本地 ref，watch current.id 时从 cases.list(current.id) 拉
-->
<template>
  <div class="page">
    <header class="header">
      <div class="header-left">
        <h1 class="title">E2E 用例列表</h1>
        <router-link to="/forms" class="link">表单设计器 →</router-link>
      </div>
      <div class="header-right">
        <span class="me">{{ me?.nickname || me?.username }}</span>
        <el-button size="small" plain @click="onLogout">退出</el-button>
      </div>
    </header>

    <!-- 空间选择器 -->
    <div class="space-bar">
      <span class="bar-label">当前空间：</span>
      <el-select
        :model-value="current?.id"
        @change="(v: string) => setCurrent(v)"
        size="default"
        style="width: 240px"
        :disabled="list.length === 0"
      >
        <el-option
          v-for="s in list"
          :key="s.id"
          :value="s.id"
          :label="`${s.name}${s.isDefault ? '（默认）' : ''} · ${roleName(s.role)}`"
        />
      </el-select>

      <template v-if="!creatingSpace">
        <el-button size="small" plain @click="creatingSpace = true">+ 新建空间</el-button>
      </template>
      <template v-else>
        <el-input
          v-model="newSpaceName"
          placeholder="空间名"
          size="default"
          style="width: 180px"
          @keydown.enter="onCreateSpace"
        />
        <el-button size="small" type="primary" @click="onCreateSpace">创建</el-button>
        <el-button size="small" plain @click="creatingSpace = false">取消</el-button>
      </template>

      <el-tag v-if="current?.isDefault" type="info" effect="plain" size="small">
        默认公共空间
      </el-tag>

      <!-- 只有 OWNER 才能管理成员 -->
      <el-button
        v-if="current?.role === 'OWNER'"
        size="small"
        plain
        @click="membersOpen = true"
      >
        成员管理
      </el-button>
    </div>

    <!-- 工具条 -->
    <div class="toolbar">
      <template v-if="!creating">
        <el-button
          type="primary"
          size="default"
          :disabled="!current"
          @click="creating = true"
        >
          + 新建用例
        </el-button>
      </template>
      <template v-else>
        <el-input
          v-model="name"
          placeholder="用例名"
          size="default"
          style="width: 240px"
          @keydown.enter="onCreate"
        />
        <el-button type="primary" size="default" @click="onCreate">创建</el-button>
        <el-button size="default" plain @click="creating = false">取消</el-button>
      </template>
    </div>

    <!-- 用例列表 -->
    <div class="case-list">
      <el-skeleton v-if="loading" :rows="4" animated />
      <el-empty
        v-else-if="caseList.length === 0"
        description="当前空间还没有用例"
      />
      <div
        v-for="c in caseList"
        :key="c.id"
        class="case-row"
      >
        <router-link :to="`/case/${c.id}`" class="case-name">
          {{ c.name }}
        </router-link>
        <span class="case-time">{{ formatTime(c.updatedAt) }}</span>
        <el-button
          size="small"
          type="danger"
          plain
          @click="onDelete(c.id)"
        >
          删除
        </el-button>
      </div>
    </div>

    <SpaceMembersDialog
      v-if="current"
      :open="membersOpen"
      :space-id="current.id"
      :space-name="current.name"
      :my-user-id="me?.id"
      @close="membersOpen = false"
    />
  </div>
</template>

<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { useRouter } from 'vue-router'
import { ElMessage, ElMessageBox } from 'element-plus'
import { cases, type CaseSummary, type SpaceRole } from '@/api'
import { useSpaceStore } from '@/stores/space'
import { useAuthStore } from '@/stores/auth'
import SpaceMembersDialog from '@/components/SpaceMembersDialog.vue'

const router = useRouter()
const auth = useAuthStore()
const me = computed(() => auth.me)
const spaceStore = useSpaceStore()
const list = computed(() => spaceStore.list)
const current = computed(() =>
  list.value.find((s) => s.id === spaceStore.currentId) ?? null,
)
const setCurrent = (id: string) => spaceStore.setCurrent(id)
const createSpace = (name: string) => spaceStore.create(name)

const caseList = ref<CaseSummary[]>([])
const loading = ref(true)

const creating = ref(false)
const name = ref('')

const creatingSpace = ref(false)
const newSpaceName = ref('')

const membersOpen = ref(false)

async function refresh() {
  if (!current.value) {
    caseList.value = []
    loading.value = false
    return
  }
  loading.value = true
  try {
    caseList.value = await cases.list(current.value.id)
  } catch (e: any) {
    ElMessage.error(e?.message ?? '加载用例失败')
  } finally {
    loading.value = false
  }
}

watch(
  () => current.value?.id,
  () => {
    refresh()
  },
  { immediate: true },
)

async function onCreate() {
  if (!name.value.trim() || !current.value) return
  try {
    const c = await cases.create(current.value.id, name.value.trim())
    name.value = ''
    creating.value = false
    router.push(`/case/${c.id}`)
  } catch (e: any) {
    ElMessage.error(e?.message ?? '创建失败')
  }
}

async function onDelete(id: string) {
  try {
    await ElMessageBox.confirm('确定删除该用例？', '提示', {
      type: 'warning',
      confirmButtonText: '删除',
      cancelButtonText: '取消',
    })
  } catch {
    return
  }
  try {
    await cases.remove(id)
    ElMessage.success('已删除')
    refresh()
  } catch (e: any) {
    ElMessage.error(e?.message ?? '删除失败')
  }
}

async function onCreateSpace() {
  const n = newSpaceName.value.trim()
  if (!n) return
  try {
    const s = await createSpace(n)
    setCurrent(s.id)
    newSpaceName.value = ''
    creatingSpace.value = false
  } catch (e: any) {
    ElMessage.error(e?.message ?? '创建空间失败')
  }
}

async function onLogout() {
  await auth.logout()
  router.replace('/login')
}

function roleName(r?: SpaceRole): string {
  switch (r) {
    case 'OWNER':
      return '所有者'
    case 'EDITOR':
      return '编辑者'
    case 'VIEWER':
      return '访客'
    default:
      return '-'
  }
}

function formatTime(ts: number): string {
  if (!ts) return ''
  return new Date(ts).toLocaleString()
}
</script>

<style scoped>
.page {
  max-width: 960px;
  margin: 0 auto;
  padding: 24px;
}
.header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 16px;
  gap: 12px;
}
.header-left {
  display: flex;
  align-items: center;
  gap: 12px;
}
.title {
  font-size: 22px;
  margin: 0;
  color: #0f172a;
}
.link {
  font-size: 12px;
  color: #0ea5e9;
}
.header-right {
  display: flex;
  align-items: center;
  gap: 8px;
  font-size: 12px;
}
.me {
  color: #64748b;
}
.space-bar {
  background: #fff;
  border: 1px solid #e2e8f0;
  border-radius: 8px;
  padding: 12px;
  margin-bottom: 16px;
  display: flex;
  align-items: center;
  gap: 12px;
  flex-wrap: wrap;
}
.bar-label {
  font-size: 12px;
  color: #64748b;
}
.toolbar {
  margin-bottom: 12px;
  display: flex;
  gap: 8px;
  align-items: center;
}
.case-list {
  background: #fff;
  border: 1px solid #e2e8f0;
  border-radius: 8px;
  overflow: hidden;
  min-height: 120px;
  padding: 4px 0;
}
.case-row {
  display: flex;
  align-items: center;
  padding: 10px 14px;
  border-top: 1px solid #f1f5f9;
  font-size: 13px;
  gap: 12px;
}
.case-row:first-child {
  border-top: none;
}
.case-name {
  color: #0f172a;
  flex: 1;
  text-decoration: none;
}
.case-name:hover {
  color: #0ea5e9;
}
.case-time {
  color: #94a3b8;
  font-size: 11px;
}
</style>

// client/src/pages/ListPage.tsx
// 列表页：当前空间下所有用例 + 空间切换 + 新建/删除
// 用 useSpaceStore + authStore 做空间与登录态
import { useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { cases, type CaseSummary, type SpaceRole } from '@/api';
import { useCurrentSpace, useSpaceStore } from '@/store/spaceStore';
import { useAuthStore } from '@/store/authStore';
import { SpaceMembersDialog } from '@/components/SpaceMembersDialog';

export function ListPage() {
  const me = useAuthStore((s) => s.me);
  const logout = useAuthStore((s) => s.logout);
  const current = useCurrentSpace();
  const list = useSpaceStore((s) => s.list);
  const setCurrent = useSpaceStore((s) => s.setCurrent);
  const createSpace = useSpaceStore((s) => s.create);

  const [caseList, setCaseList] = useState<CaseSummary[]>([]);
  const [loading, setLoading] = useState(true);
  const [creating, setCreating] = useState(false);
  const [name, setName] = useState('');
  const [creatingSpace, setCreatingSpace] = useState(false);
  const [newSpaceName, setNewSpaceName] = useState('');
  const [membersOpen, setMembersOpen] = useState(false);
  const navigate = useNavigate();

  const refresh = async () => {
    if (!current) return;
    setLoading(true);
    try {
      setCaseList(await cases.list(current.id));
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    refresh();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [current?.id]);

  const onCreate = async () => {
    if (!name.trim() || !current) return;
    const c = await cases.create(current.id, name.trim());
    setName('');
    setCreating(false);
    navigate(`/case/${c.id}`);
  };

  const onDelete = async (id: string) => {
    if (!confirm('确定删除该用例？')) return;
    await cases.remove(id);
    refresh();
  };

  const onCreateSpace = async () => {
    const n = newSpaceName.trim();
    if (!n) return;
    const s = await createSpace(n);
    setCurrent(s.id);
    setNewSpaceName('');
    setCreatingSpace(false);
    refresh();
  };

  return (
    <div style={{ maxWidth: 960, margin: '0 auto', padding: 24 }}>
      <header
        style={{
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          marginBottom: 16,
          gap: 12,
        }}
      >
        <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
          <h1 style={{ fontSize: 22, margin: 0 }}>E2E 用例列表</h1>
          <Link
            to="/forms"
            style={{ fontSize: 12, color: '#0ea5e9', textDecoration: 'none' }}
          >
            表单设计器 →
          </Link>
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8, fontSize: 12 }}>
          <span style={{ color: '#64748b' }}>{me?.nickname || me?.username}</span>
          <button
            onClick={async () => {
              await logout();
              navigate('/login', { replace: true });
            }}
            style={btnGhost}
          >
            退出
          </button>
        </div>
      </header>

      {/* 空间选择器 */}
      <div
        style={{
          background: '#fff',
          border: '1px solid #e2e8f0',
          borderRadius: 8,
          padding: 12,
          marginBottom: 16,
          display: 'flex',
          alignItems: 'center',
          gap: 12,
          flexWrap: 'wrap',
        }}
      >
        <span style={{ fontSize: 12, color: '#64748b' }}>当前空间：</span>
        <select
          value={current?.id ?? ''}
          onChange={(e) => setCurrent(e.target.value)}
          style={{
            padding: '4px 8px',
            border: '1px solid #cbd5e1',
            borderRadius: 6,
            fontSize: 13,
            background: '#fff',
          }}
        >
          {list.map((s) => (
            <option key={s.id} value={s.id}>
              {s.name}
              {s.isDefault ? ' (默认)' : ''} · 角色 {roleName(s.role)}
            </option>
          ))}
        </select>
        {!creatingSpace ? (
          <button onClick={() => setCreatingSpace(true)} style={btnGhost}>
            + 新建空间
          </button>
        ) : (
          <>
            <input
              autoFocus
              placeholder="空间名"
              value={newSpaceName}
              onChange={(e) => setNewSpaceName(e.target.value)}
              onKeyDown={(e) => e.key === 'Enter' && onCreateSpace()}
              style={{
                padding: '4px 8px',
                border: '1px solid #cbd5e1',
                borderRadius: 6,
                fontSize: 13,
              }}
            />
            <button onClick={onCreateSpace} style={btnPrimary}>
              创建
            </button>
            <button onClick={() => setCreatingSpace(false)} style={btnGhost}>
              取消
            </button>
          </>
        )}
        {current?.isDefault && (
          <span
            style={{
              fontSize: 11,
              color: '#0ea5e9',
              background: '#e0f2fe',
              padding: '2px 8px',
              borderRadius: 999,
            }}
          >
            默认公共空间
          </span>
        )}
        {/* 只有 OWNER 才能管理成员 */}
        {current?.role === 'OWNER' && (
          <button onClick={() => setMembersOpen(true)} style={btnGhost}>
            成员管理
          </button>
        )}
      </div>

      {/* 工具条 */}
      <div style={{ marginBottom: 12, display: 'flex', gap: 8 }}>
        {!creating ? (
          <button
            onClick={() => setCreating(true)}
            disabled={!current}
            style={{
              ...btnPrimary,
              opacity: current ? 1 : 0.5,
            }}
          >
            + 新建用例
          </button>
        ) : (
          <>
            <input
              autoFocus
              placeholder="用例名"
              value={name}
              onChange={(e) => setName(e.target.value)}
              onKeyDown={(e) => e.key === 'Enter' && onCreate()}
              style={{
                padding: '6px 10px',
                border: '1px solid #cbd5e1',
                borderRadius: 6,
                fontSize: 13,
              }}
            />
            <button onClick={onCreate} style={btnPrimary}>
              创建
            </button>
            <button onClick={() => setCreating(false)} style={btnGhost}>
              取消
            </button>
          </>
        )}
      </div>

      {/* 用例表 */}
      <div
        style={{
          background: '#fff',
          border: '1px solid #e2e8f0',
          borderRadius: 8,
          overflow: 'hidden',
        }}
      >
        {loading ? (
          <div style={{ padding: 24, color: '#64748b', textAlign: 'center' }}>加载中…</div>
        ) : caseList.length === 0 ? (
          <div style={{ padding: 24, color: '#94a3b8', textAlign: 'center' }}>
            当前空间还没有用例
          </div>
        ) : (
          caseList.map((c, i) => (
            <div
              key={c.id}
              style={{
                display: 'flex',
                alignItems: 'center',
                padding: '10px 14px',
                borderTop: i === 0 ? 'none' : '1px solid #f1f5f9',
                fontSize: 13,
              }}
            >
              <Link
                to={`/case/${c.id}`}
                style={{ color: '#0f172a', textDecoration: 'none', flex: 1 }}
              >
                {c.name}
              </Link>
              <span style={{ color: '#94a3b8', fontSize: 11, marginRight: 12 }}>
                {new Date(c.updatedAt).toLocaleString()}
              </span>
              <button
                onClick={() => onDelete(c.id)}
                style={{
                  background: 'transparent',
                  color: '#dc2626',
                  border: '1px solid #fecaca',
                  padding: '2px 8px',
                  borderRadius: 4,
                  cursor: 'pointer',
                  fontSize: 11,
                }}
              >
                删除
              </button>
            </div>
          ))
        )}
      </div>

      {current && (
        <SpaceMembersDialog
          open={membersOpen}
          onClose={() => setMembersOpen(false)}
          spaceId={current.id}
          spaceName={current.name}
          myUserId={me?.id}
        />
      )}
    </div>
  );
}

const btnPrimary: React.CSSProperties = {
  background: '#0f172a',
  color: '#fff',
  border: 'none',
  padding: '6px 12px',
  borderRadius: 6,
  fontSize: 12,
  cursor: 'pointer',
};
const btnGhost: React.CSSProperties = {
  background: '#fff',
  color: '#0f172a',
  border: '1px solid #cbd5e1',
  padding: '4px 10px',
  borderRadius: 6,
  fontSize: 12,
  cursor: 'pointer',
};

function roleName(r?: SpaceRole): string {
  switch (r) {
    case 'OWNER':
      return '所有者';
    case 'EDITOR':
      return '编辑者';
    case 'VIEWER':
      return '访客';
    default:
      return '-';
  }
}
