// client/src/pages/LoginPage.tsx
// 登录页：极简版 — 用户名 / 密码 / 注册 / 登录
// 注册接口默认会绑定到 common 空间，无需选空间
import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuthStore } from '@/store/authStore';

export function LoginPage() {
  const navigate = useNavigate();
  const { login, register } = useAuthStore();
  const [mode, setMode] = useState<'login' | 'register'>('login');
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [nickname, setNickname] = useState('');
  const [error, setError] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);

  const submit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError(null);
    setBusy(true);
    try {
      if (mode === 'login') {
        await login(username.trim(), password);
      } else {
        await register(username.trim(), password, nickname.trim() || undefined);
      }
      navigate('/', { replace: true });
    } catch (e: any) {
      setError(e?.message ?? '操作失败');
    } finally {
      setBusy(false);
    }
  };

  return (
    <div
      style={{
        minHeight: '100vh',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        background: '#f1f5f9',
      }}
    >
      <form
        onSubmit={submit}
        style={{
          width: 360,
          background: '#fff',
          padding: 28,
          borderRadius: 12,
          boxShadow: '0 6px 24px rgba(15,23,42,0.08)',
        }}
      >
        <h1 style={{ margin: 0, fontSize: 22, color: '#0f172a' }}>
          E2E Orchestrator
        </h1>
        <div style={{ fontSize: 12, color: '#64748b', marginBottom: 18, marginTop: 4 }}>
          {mode === 'login' ? '登录后继续' : '注册账号（自动加入公共空间）'}
        </div>

        <Field label="用户名">
          <input
            value={username}
            onChange={(e) => setUsername(e.target.value)}
            autoFocus
            required
            minLength={3}
            style={inputStyle}
          />
        </Field>
        <Field label="密码">
          <input
            type="password"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            required
            minLength={6}
            style={inputStyle}
          />
        </Field>
        {mode === 'register' && (
          <Field label="昵称（可选）">
            <input
              value={nickname}
              onChange={(e) => setNickname(e.target.value)}
              style={inputStyle}
            />
          </Field>
        )}

        {error && (
          <div
            style={{
              color: '#dc2626',
              background: '#fef2f2',
              border: '1px solid #fecaca',
              padding: '6px 10px',
              borderRadius: 6,
              fontSize: 12,
              marginBottom: 12,
            }}
          >
            {error}
          </div>
        )}

        <button
          type="submit"
          disabled={busy}
          style={{
            width: '100%',
            padding: '10px 0',
            background: busy ? '#94a3b8' : '#0f172a',
            color: '#fff',
            border: 'none',
            borderRadius: 6,
            fontSize: 14,
            cursor: busy ? 'not-allowed' : 'pointer',
          }}
        >
          {busy ? '处理中…' : mode === 'login' ? '登录' : '注册'}
        </button>

        <div style={{ marginTop: 12, fontSize: 12, color: '#64748b', textAlign: 'center' }}>
          {mode === 'login' ? (
            <>
              还没有账号？{' '}
              <a
                onClick={() => setMode('register')}
                style={{ color: '#0ea5e9', cursor: 'pointer' }}
              >
                立即注册
              </a>
            </>
          ) : (
            <>
              已有账号？{' '}
              <a
                onClick={() => setMode('login')}
                style={{ color: '#0ea5e9', cursor: 'pointer' }}
              >
                返回登录
              </a>
            </>
          )}
        </div>
      </form>
    </div>
  );
}

const inputStyle: React.CSSProperties = {
  width: '100%',
  padding: '8px 10px',
  border: '1px solid #cbd5e1',
  borderRadius: 6,
  fontSize: 13,
  boxSizing: 'border-box',
};

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <label style={{ display: 'block', marginBottom: 12 }}>
      <div style={{ fontSize: 12, color: '#475569', marginBottom: 4 }}>{label}</div>
      {children}
    </label>
  );
}

// client-vue/src/pages/LoginPage.vue
<template>
  <div class="login-page">
    <el-card class="login-card" shadow="hover">
      <template #header>
        <div class="header">
          <h1 class="title">E2E Orchestrator</h1>
          <span class="subtitle">Vue 3 + Element Plus 版</span>
        </div>
      </template>

      <el-tabs v-model="mode" class="tabs">
        <el-tab-pane label="登录" name="login" />
        <el-tab-pane label="注册" name="register" />
      </el-tabs>

      <el-form ref="formRef" :model="form" :rules="rules" label-position="top" @submit.prevent>
        <el-form-item label="用户名" prop="username">
          <el-input
            v-model="form.username"
            placeholder="至少 3 个字符"
            autocomplete="username"
            autofocus
          />
        </el-form-item>

        <el-form-item label="密码" prop="password">
          <el-input
            v-model="form.password"
            type="password"
            placeholder="至少 6 个字符"
            show-password
            autocomplete="current-password"
            @keyup.enter="submit"
          />
        </el-form-item>

        <el-form-item v-if="mode === 'register'" label="昵称（可选）" prop="nickname">
          <el-input v-model="form.nickname" placeholder="留空则使用用户名" />
        </el-form-item>

        <el-alert
          v-if="errorMsg"
          :title="errorMsg"
          type="error"
          :closable="false"
          show-icon
          class="alert"
        />

        <el-button
          type="primary"
          native-type="submit"
          :loading="busy"
          class="submit"
          @click="submit"
        >
          {{ mode === 'login' ? '登录' : '注册' }}
        </el-button>

        <div class="tip">
          {{ mode === 'login' ? '注册会自动加入公共空间' : '已有账号？' }}
          <a v-if="mode === 'login'" @click="mode = 'register'">立即注册</a>
          <a v-else @click="mode = 'login'">返回登录</a>
        </div>
      </el-form>
    </el-card>
  </div>
</template>

<script setup lang="ts">
import { reactive, ref } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import { ElMessage, type FormInstance, type FormRules } from 'element-plus'
import { useAuthStore } from '@/stores/auth'

const auth = useAuthStore()
const router = useRouter()
const route = useRoute()

const mode = ref<'login' | 'register'>('login')
const formRef = ref<FormInstance>()
const busy = ref(false)
const errorMsg = ref<string | null>(null)

const form = reactive({
  username: '',
  password: '',
  nickname: '',
})

const rules: FormRules = {
  username: [{ required: true, min: 3, message: '至少 3 个字符', trigger: 'blur' }],
  password: [{ required: true, min: 6, message: '至少 6 个字符', trigger: 'blur' }],
}

async function submit() {
  errorMsg.value = null
  if (!formRef.value) return
  const valid = await formRef.value.validate().catch(() => false)
  if (!valid) return
  busy.value = true
  try {
    if (mode.value === 'login') {
      await auth.login(form.username.trim(), form.password)
    } else {
      await auth.register(form.username.trim(), form.password, form.nickname.trim() || undefined)
    }
    ElMessage.success(mode.value === 'login' ? '登录成功' : '注册成功')
    const redirect = (route.query.redirect as string) || '/'
    router.replace(redirect)
  } catch (e: any) {
    errorMsg.value = e?.message ?? '操作失败'
  } finally {
    busy.value = false
  }
}
</script>

<style scoped>
.login-page {
  min-height: 100vh;
  display: flex;
  align-items: center;
  justify-content: center;
  background: linear-gradient(135deg, #f1f5f9 0%, #e2e8f0 100%);
  padding: 20px;
}

.login-card {
  width: 400px;
  border-radius: 12px;
}

.header {
  display: flex;
  flex-direction: column;
  gap: 4px;
}

.title {
  margin: 0;
  font-size: 22px;
  color: #0f172a;
}

.subtitle {
  font-size: 12px;
  color: #64748b;
}

.tabs {
  margin-bottom: 16px;
}

.alert {
  margin-bottom: 16px;
}

.submit {
  width: 100%;
  height: 40px;
  font-size: 14px;
}

.tip {
  margin-top: 12px;
  font-size: 12px;
  color: #64748b;
  text-align: center;
}

.tip a {
  margin-left: 4px;
  cursor: pointer;
  color: #0ea5e9;
}

.tip a:hover {
  text-decoration: underline;
}
</style>
